### PR TITLE
Create java_intro.md

### PR DESCRIPTION
**Pull request by abhisek247767**
Add Java's History and features

### CODE REVIEW

**Comment by abhisek247767** [comment]
Please check :)

**Comment by abhisek247767** [comment]
someone Please review 😢

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please improve this one it looks like it is mostly copy from the https://manjujava.wordpress.com/

**Comment by abhisek247767** [comment]
Please check my updated blog.

**Comment by abhisek247767** [comment]
Please someone review my work

**Review by pragyaasapkota — CHANGES_REQUESTED** [review]
image

**Comment by pragyaasapkota** [comment]
This is a plagiarized content.

**Comment by pragyaasapkota** [comment]
Your content should be unique. 
The above content was 62% copied which might be unacceptable -- The reason your PR wasn't merged.

**Comment by ZoranPandovski** [comment]
Thanks for the review @Pragya2056

**Pull request closed without merging**
