### PR TITLE
added relational database

### PR DESCRIPTION
**Pull request by Pragya2056**
Added the file relational database

### CODE REVIEW

**Comment by Pragya2056** [comment]
The issue #233

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please add the metadata in the header with required info e.g https://raw.githubusercontent.com/flashreads/blogs/master/template.md

**Comment by Pragya2056** [comment]
@ZoranPandovski 
Please review the changes

**Review by natemago — APPROVED** [review]
LGTM

**Pull request merged**
